---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ltcSway-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - clone-dotfiles.sh

  - type: rpm-ostree
    install:
      - zsh
      - stow
      - neovim
      - gammastep
      - boxes

    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - install:
          - com.stremio.Stremio
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.transmissionbt.Transmission
          - com.spotify.Client
          - org.freedesktop.Platform.ffmpeg-full

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

